version: '3'
services:
  postgres_db:
    image: postgres:14-alpine
    container_name: "postgres10.1"
    environment:
      POSTGRES_PASSWORD: "${PSQL_PASS}"
      POSTGRES_DB: "${PSQL_DB}"
      POSTGRES_USER: "${PSQL_USER}"
    ports:
      - "100${PORT}:55${PORT}"
    volumes:
      - "${POSTGRES_VOLUME_PATH}:/usr/src/postgres"
    networks:
      - our-library-net
    command: -p "55${PORT}"

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8010"
    container_name: "django10.1"
    environment:
      PSQL_DBNAME: "${PSQL_DB}"
      PSQL_USERNAME: "${PSQL_USER}"
      PSQL_PASS: "${PSQL_PASS}"
      PSQL_HOST: "postgres_db"
      PSQL_PORT: "55${PORT}"
      JWT_TOKEN_TIME: "${JWT_TOKEN_TIME}"
    volumes:
      - "${DJANGO_VOLUME_PATH}:/usr/src/django/fantasylabs"
    ports:
      - "90${PORT}:80${PORT}"
    networks:
      - our-library-net

  front:
    build:
      dockerfile: Dockerfile
      context: ./world
    command: sh -c "yarn install && yarn run start"
    container_name: "react${PORT}"
    volumes:
      - "${REACT_VOLUME_PATH}:/app"
    ports:
      - "110${PORT}:110${PORT}"
    networks:
      - our-library-net

networks:
  our-library-net:
    external: true
    driver: bridge