# Generated by Django 4.0.3 on 2022-04-27 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('singers', '0001_initial'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('release_date', models.DateField()),
                ('duration', models.SmallIntegerField()),
                ('complete_file', models.BinaryField()),
                ('preview_file', models.BinaryField()),
                ('price', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SongsSingers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SingerWithSongs', to='singers.singer')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SongWithSingers', to='songs.song')),
            ],
        ),
        migrations.CreateModel(
            name='SongsAlbums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='AlbumWithSongs', to='albums.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SongWithAlbums', to='songs.song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(through='songs.SongsAlbums', to='albums.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ManyToManyField(through='songs.SongsSingers', to='singers.singer'),
        ),
    ]
