# Generated by Django 4.0.3 on 2022-05-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='complete_file',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='preview_file',
            field=models.TextField(),
        ),
    ]
